Resources:
  BoardDynamoDBTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        -
          AttributeName: pk
          AttributeType: S
        -
          AttributeName: sk
          AttributeType: S
        -
          AttributeName: userid
          AttributeType: S
      KeySchema:
        -
          AttributeName: pk
          KeyType: HASH
        -
          AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.currentVars.tableName}
      Tags:
        - Key: Application
          Value: custcenter
        - Key: Service
          Value: bbs
        - Key: Role
          Value: db
        - Key: Owner
          Value: KimByoungChul
      GlobalSecondaryIndexes:
        -
          IndexName: userIndex
          KeySchema:
            -
              AttributeName: userid
              KeyType: HASH
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
            - password